packages:
  - "frontend"
  - "backend"
  - "package"

catalog:
  "@inquirer/prompts": "^8.3.2"
  "@biomejs/biome": "^1.9.4"
  "@imgly/background-removal": "^1.4.5"
  "@imgly/background-removal-node": "^1.4.5"
  "@rslib/core": "^0.12.2"
  "@types/node": "^24.6.0"
  "@types/pdfkit": "^0.17.3"
  "axios": "^1.13.4"
  "cheerio": "^1.1.2"
  "commander": "^14.0.1"
  "docx": "^9.5.1"
  "fast-glob": "^3.3.3"
  "ffmpeg-static": "^5.2.0"
  "husky": "^9.1.7"
  "jsqr": "^1.4.0"
  "marked": "^16.4.2"
  "papaparse": "^5.5.3"
  "pdf-lib": "^1.17.1"
  "pdf-parse": "^1.1.4"
  "pdfkit": "^0.17.2"
  "react": "^19.2.4"
  "react-dom": "^19.2.4"
  "jimp": "^1.6.0"
  "@jimp/wasm-webp": "^1.6.0"
  "@jimp/wasm-avif": "^1.6.0"
  "sharp": "^0.33.5"
  "reclaimspace": "^0.2.1"
  "tsx": "^4.20.6"
  "turbo": "^2.8.1"
  "turndown": "^7.2.2"
  "typescript": "^5.9.3"
  "xlsx": "^0.18.5"
  "@distube/ytdl-core": "^4.16.2"
  "youtubei.js": "^17.0.1"
